name: Test dispatch
on:
  workflow_dispatch:
    inputs:
      dummy: { description: 'just a test', required: false, type: string }

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "It works!"
